[workspace]
resolver = "2"
members = ["crates/gitreqd-core", "crates/gitreqd", "crates/gitreqd-macros"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.4.0"

[workspace.dependencies]
gitreqd-core = { path = "crates/gitreqd-core" }
gitreqd-macros = { path = "crates/gitreqd-macros" }
serde = { version = "1", features = ["derive"] }
syn = { version = "2", features = ["full", "visit", "parsing"] }
quote = "1"
proc-macro2 = { version = "1", features = ["span-locations"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror = "1"
walkdir = "2"
regex = "1"
indexmap = "=2.7.1"
pulldown-cmark = { version = "=0.12.2", default-features = false, features = ["html"] }
clap = { version = "=4.5.23", features = ["derive"] }
anyhow = "1"
