/**
 * GRD-VSC-003: Requirement editor preview — dedicated webview, shared HTML base with full report,
 * editor title Preview button, side-by-side view; switching editor or opening a requirement file
 * (e.g. via satisfies link) shows that requirement’s preview.
 *
 * Preview HTML is generated by core's generateSingleRequirementHtml, which uses the same
 * requirementDetailHtml as the full report — so description and rationale are rendered as
 * Markdown (GRD-HTML-004) and styling matches the exported HTML report.
 */
import * as path from "path";
import * as vscode from "vscode";
import { generateSingleRequirementHtml, loadRequirements } from "@gitreqd/core";
import type { ParameterValue, RequirementWithSource } from "@gitreqd/core";
import { parse as parseYaml } from "yaml";

function previewTitle(uri: vscode.Uri): string {
  return `Requirement Preview: ${path.basename(uri.fsPath)}`;
}

const PREVIEW_VIEW_TYPE = "gitreqd.requirementPreview";

/** Script injected so that clicking a "satisfies" link in the preview opens that requirement's preview (GRD-VSC-003). */
const PREVIEW_LINK_SCRIPT =
  `
<script>
(function() {
  const vscode = acquireVsCodeApi();
  document.querySelectorAll('a[href^="#"]').forEach(function(a) {
    a.addEventListener('click', function(e) {
      var href = a.getAttribute('href');
      if (href && href.length > 1) {
        e.preventDefault();
        vscode.postMessage({ type: 'openPreview', requirementId: href.slice(1) });
      }
    });
  });
})();
</scr` +
  `ipt>
`;

function parseRequirementFromText(
  uri: vscode.Uri,
  text: string
): RequirementWithSource {
  const data = parseYaml(text) as Record<string, unknown> | null;
  if (!data || typeof data !== "object") {
    throw new Error("Expected a YAML object with requirement fields.");
  }

  const id = data.id != null ? String(data.id) : undefined;
  const title = data.title != null ? String(data.title) : undefined;
  const description = data.description != null ? String(data.description) : "";

  if (!id) {
    throw new Error("Missing required field: id");
  }
  if (!title) {
    throw new Error("Missing required field: title");
  }

  // GRD-SYS-005: Parse parameters (name -> string | number | boolean) so preview resolves {{ :param }}.
  const parameters = normalizeParameters(data.parameters);

  const requirement: RequirementWithSource = {
    id,
    title,
    description,
    attributes:
      typeof data.attributes === "object" && data.attributes !== null
        ? (data.attributes as Record<string, unknown>)
        : undefined,
    links: Array.isArray(data.links) ? (data.links as RequirementWithSource["links"]) : undefined,
    parameters: parameters && Object.keys(parameters).length > 0 ? parameters : undefined,
    sourcePath: uri.fsPath,
  };

  return requirement;
}

/** GRD-SYS-005: Normalize YAML parameters to Record<string, ParameterValue>. */
function normalizeParameters(parameters: unknown): Record<string, ParameterValue> | undefined {
  if (parameters == null || typeof parameters !== "object" || Array.isArray(parameters)) {
    return undefined;
  }
  const out: Record<string, ParameterValue> = {};
  for (const [k, v] of Object.entries(parameters as Record<string, unknown>)) {
    if (typeof k !== "string" || !k.trim()) continue;
    if (v === null || v === undefined) continue;
    if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") {
      out[k] = v;
    }
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

export type OpenPreviewForIdFn = (requirementId: string) => Promise<void>;

export class RequirementPreviewManager {
  private panel: vscode.WebviewPanel | undefined;
  private currentDocumentUri: string | undefined;

  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly log: (message: string) => void,
    private readonly openPreviewForId: OpenPreviewForIdFn
  ) {
    const changeSub = vscode.workspace.onDidChangeTextDocument((e) => {
      if (this.currentDocumentUri !== e.document.uri.toString()) return;
      this.updatePreview(e.document);
    });

    const saveSub = vscode.workspace.onDidSaveTextDocument((doc) => {
      if (this.currentDocumentUri !== doc.uri.toString()) return;
      this.updatePreview(doc);
    });

    const activeEditorSub = vscode.window.onDidChangeActiveTextEditor((editor) => {
      if (!editor) return;
      const doc = editor.document;
      if (doc.languageId !== "yaml") return;
      // GRD-VSC-003: When user clicks a satisfies link, the target file opens and becomes active;
      // open the preview for that requirement if the panel did not exist yet.
      if (!this.panel) {
        this.openPreviewForDocument(doc);
        return;
      }
      const uri = doc.uri.toString();
      if (uri === this.currentDocumentUri) return;
      this.currentDocumentUri = uri;
      this.panel.title = previewTitle(doc.uri);
      this.updatePreview(doc);
    });

    context.subscriptions.push(changeSub, saveSub, activeEditorSub);
  }

  openPreviewForDocument(document: vscode.TextDocument): void {
    if (document.languageId !== "yaml") {
      this.log("[Gitreqd] Preview is only available for YAML requirement files.");
      return;
    }

    this.currentDocumentUri = document.uri.toString();

    if (this.panel) {
      this.panel.title = previewTitle(document.uri);
      this.updatePreview(document);
      this.panel.reveal(this.panel.viewColumn ?? vscode.ViewColumn.Beside);
      return;
    }

    this.panel = vscode.window.createWebviewPanel(
      PREVIEW_VIEW_TYPE,
      previewTitle(document.uri),
      vscode.ViewColumn.Beside,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
      }
    );

    this.context.subscriptions.push(this.panel);

    this.panel.onDidDispose(
      () => {
        this.panel = undefined;
        this.currentDocumentUri = undefined;
      },
      undefined,
      this.context.subscriptions
    );

    this.panel.webview.onDidReceiveMessage(
      (msg: { type?: string; requirementId?: string }) => {
        if (msg.type === "openPreview" && typeof msg.requirementId === "string") {
          this.openPreviewForId(msg.requirementId).catch((err) =>
            this.log(`[Gitreqd] Failed to open preview for ${msg.requirementId}: ${String(err)}`)
          );
        }
      },
      undefined,
      this.context.subscriptions
    );

    this.updatePreview(document);
  }

  /** Injects script so satisfies links in the preview HTML open the target requirement's preview. */
  private injectPreviewLinkHandler(html: string): string {
    if (html.includes("</body>")) {
      return html.replace("</body>", PREVIEW_LINK_SCRIPT + "\n</body>");
    }
    return html + PREVIEW_LINK_SCRIPT;
  }

  private async updatePreview(document: vscode.TextDocument): Promise<void> {
    if (!this.panel || this.currentDocumentUri !== document.uri.toString()) return;

    try {
      const requirement = parseRequirementFromText(
        document.uri,
        document.getText()
      );
      let allRequirements: RequirementWithSource[] | undefined;
      const folder = vscode.workspace.getWorkspaceFolder(document.uri);
      if (folder) {
        try {
          const result = await loadRequirements(folder.uri.fsPath);
          let list = result.requirements;
          const idx = list.findIndex((r) => r.id === requirement.id);
          if (idx >= 0) {
            list = [...list];
            list[idx] = requirement;
          } else {
            list = [requirement, ...list];
          }
          allRequirements = list;
        } catch {
          allRequirements = undefined;
        }
      }
      const baseHtml = generateSingleRequirementHtml(requirement, allRequirements);
      this.panel.webview.html = this.injectPreviewLinkHandler(baseHtml);
    } catch (err) {
      const message = `[Gitreqd] Failed to render preview for ${document.uri.fsPath}: ${String(
        err
      )}`;
      this.log(message);
      this.panel.webview.html = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <title>Gitreqd requirement preview error</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 1rem; color: #b00020; }
            pre { white-space: pre-wrap; background: #fef2f2; padding: 0.75rem; border-radius: 4px; }
          </style>
        </head>
        <body>
          <h1>Could not render requirement preview</h1>
          <p>There was an error parsing the YAML or generating HTML:</p>
          <pre>${String(err)}</pre>
        </body>
        </html>
      `;
    }
  }

}

