/**
 * GRD-VSC-003: Requirement editor preview — dedicated webview, shared HTML base with full report,
 * editor title Preview button, side-by-side view; switching editor or opening a requirement file
 * (e.g. via satisfies link) shows that requirement’s preview.
 *
 * GRD-VSC-006: Editable description and rationale use Toast UI (WYSIWYG) in the webview; raw Markdown
 * is edited in the YAML editor. Updates apply back to the file; structure-only changes re-render HTML,
 * text-only edits sync field state without replacing the webview document.
 *
 * Preview HTML is generated by the active profile's generateSingleRequirementHtml, which uses the same
 * requirementDetailHtml as the full report — so description and rationale are rendered as
 * Markdown (GRD-HTML-004) and styling matches the exported HTML report.
 */
import * as path from "path";
import * as vscode from "vscode";
import {
  discoverProjectRoot,
  getRequirementProfile,
  loadActiveProfile,
  loadRequirements,
  STANDARD_PROFILE_ID,
} from "@gitreqd/core";
import type { RequirementProfile } from "@gitreqd/core";
import type { ParameterValue, RequirementWithSource } from "@gitreqd/core";
import { parse as parseYaml } from "yaml";
import { isRequirementDocument } from "./requirement-document.js";
import {
  applyYamlMarkdownFieldUpdate,
  type EditableMarkdownField,
} from "./yaml-field-patch.js";

function previewTitle(uri: vscode.Uri): string {
  return `Requirement Preview: ${path.basename(uri.fsPath)}`;
}

const PREVIEW_VIEW_TYPE = "gitreqd.requirementPreview";

/** GRD-VSC-003: Delegated click handler so links work after WYSIWYG updates (GRD-VSC-006). */
const PREVIEW_LINK_SCRIPT =
  `
<script>
(function() {
  const vscode = acquireVsCodeApi();
  document.body.addEventListener('click', function(e) {
    var t = e.target;
    if (!t || !t.closest) return;
    var a = t.closest('a[href^="#"]');
    if (!a) return;
    var href = a.getAttribute('href');
    if (href && href.length > 1) {
      e.preventDefault();
      e.stopPropagation();
      vscode.postMessage({ type: 'openPreview', requirementId: href.slice(1) });
    }
  });
})();
</scr` +
  `ipt>
`;

/** VSCode theme variables for preview + Toast UI chrome (GRD-VSC-006). Toast defaults use #333/#555; override for contrast. */
const PREVIEW_VSCODE_CHROME_STYLES = `
body { background-color: var(--vscode-editor-background); color: var(--vscode-editor-foreground); }
.requirement-detail .label { color: var(--vscode-foreground); }
.requirement-detail h2 { color: var(--vscode-foreground); }
.meta, .source { color: var(--vscode-descriptionForeground); }
.param-value { background: var(--vscode-textCodeBlock-background); color: var(--vscode-textPreformat-foreground); }
.parameters-table th { background: var(--vscode-editorWidget-background); color: var(--vscode-foreground); }
.parameters-table td, .parameters-table th { border-color: var(--vscode-panel-border); }
.toastui-editor-defaultUI {
  border-color: var(--vscode-widget-border);
  border-radius: 4px;
  background: var(--vscode-editor-background);
  color: var(--vscode-editor-foreground);
}
.toastui-editor-defaultUI-toolbar {
  background: var(--vscode-editorWidget-background) !important;
  border-bottom-color: var(--vscode-widget-border) !important;
}
.toastui-editor-defaultUI-toolbar button:not(:disabled):hover {
  background-color: var(--vscode-toolbar-hoverBackground) !important;
  border-color: var(--vscode-widget-border) !important;
}
.toastui-editor-defaultUI-toolbar .scroll-sync {
  color: var(--vscode-descriptionForeground) !important;
}
/* Toolbar sprites are dark-grey on light; invert on dark / HC-dark so icons stay visible. */
body.vscode-dark .toastui-editor-toolbar-icons,
body.vscode-high-contrast .toastui-editor-toolbar-icons {
  filter: invert(1) brightness(1.15);
}
body.vscode-dark .toastui-editor-toolbar-icons:not(:disabled).active,
body.vscode-high-contrast .toastui-editor-toolbar-icons:not(:disabled).active {
  filter: invert(1) brightness(1.35);
}
body.vscode-high-contrast-light .toastui-editor-toolbar-icons {
  filter: none !important;
}
.toastui-editor-contents {
  font-family: var(--vscode-font-family);
  font-size: var(--vscode-editor-font-size);
  color: var(--vscode-editor-foreground) !important;
}
.toastui-editor-md-container .toastui-editor,
.toastui-editor-ww-container .toastui-editor {
  background: var(--vscode-editor-background) !important;
  color: var(--vscode-editor-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror,
.toastui-editor-ww-container .ProseMirror p,
.toastui-editor-ww-container .ProseMirror li,
.toastui-editor-ww-container .ProseMirror td,
.toastui-editor-ww-container .ProseMirror th {
  color: var(--vscode-editor-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror h1,
.toastui-editor-ww-container .ProseMirror h2,
.toastui-editor-ww-container .ProseMirror h3,
.toastui-editor-ww-container .ProseMirror h4,
.toastui-editor-ww-container .ProseMirror h5,
.toastui-editor-ww-container .ProseMirror h6 {
  color: var(--vscode-editor-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror a {
  color: var(--vscode-textLink-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror blockquote {
  border-left-color: var(--vscode-editorWidget-border, var(--vscode-widget-border));
  color: var(--vscode-editor-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror code {
  background-color: var(--vscode-textCodeBlock-background);
  color: var(--vscode-textPreformat-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror pre {
  background-color: var(--vscode-textCodeBlock-background) !important;
  color: var(--vscode-editor-foreground) !important;
}
.toastui-editor-ww-container .ProseMirror pre code {
  background: transparent !important;
  color: inherit !important;
}
.toastui-editor-ww-container .ProseMirror hr {
  border-color: var(--vscode-widget-border);
}
.toastui-editor-ww-container .ProseMirror table {
  border-color: var(--vscode-widget-border);
}
.toastui-editor-ww-container .ProseMirror th,
.toastui-editor-ww-container .ProseMirror td {
  border-color: var(--vscode-widget-border) !important;
}
/* Toast popups keep #fff background but inherit body/editor text color → illegible in dark themes. */
.toastui-editor-popup {
  background-color: var(--vscode-editorWidget-background) !important;
  border-color: var(--vscode-editorWidget-border, var(--vscode-widget-border)) !important;
  color: var(--vscode-editorWidget-foreground, var(--vscode-foreground)) !important;
  box-shadow: 0 2px 8px var(--vscode-widget-shadow, rgba(0, 0, 0, 0.36));
}
.toastui-editor-popup-body label {
  color: var(--vscode-editorWidget-foreground, var(--vscode-foreground)) !important;
}
.toastui-editor-popup-body input[type='text'] {
  background-color: var(--vscode-input-background) !important;
  color: var(--vscode-input-foreground) !important;
  border-color: var(--vscode-input-border, var(--vscode-widget-border)) !important;
}
.toastui-editor-popup-body input[type='text']:focus {
  outline-color: var(--vscode-focusBorder) !important;
}
.toastui-editor-popup-body input[type='text'].disabled {
  background-color: var(--vscode-input-background) !important;
  color: var(--vscode-disabledForeground) !important;
}
.toastui-editor-dropdown-toolbar {
  background-color: var(--vscode-editorWidget-background) !important;
  border-color: var(--vscode-editorWidget-border, var(--vscode-widget-border)) !important;
  box-shadow: 0 2px 8px var(--vscode-widget-shadow, rgba(0, 0, 0, 0.36));
}
/* Heading level picker: list + preview headings use theme foreground on widget background. */
.toastui-editor-popup-add-heading ul li,
.toastui-editor-popup-add-heading ul li h1,
.toastui-editor-popup-add-heading ul li h2,
.toastui-editor-popup-add-heading ul li h3,
.toastui-editor-popup-add-heading ul li h4,
.toastui-editor-popup-add-heading ul li h5,
.toastui-editor-popup-add-heading ul li h6,
.toastui-editor-popup-add-heading ul li p {
  color: var(--vscode-editorWidget-foreground, var(--vscode-foreground)) !important;
}
.toastui-editor-popup-add-heading ul li:hover {
  background-color: var(--vscode-list-hoverBackground) !important;
}
.toastui-editor-popup-add-heading ul li:hover h1,
.toastui-editor-popup-add-heading ul li:hover h2,
.toastui-editor-popup-add-heading ul li:hover h3,
.toastui-editor-popup-add-heading ul li:hover h4,
.toastui-editor-popup-add-heading ul li:hover h5,
.toastui-editor-popup-add-heading ul li:hover h6,
.toastui-editor-popup-add-heading ul li:hover p {
  color: var(--vscode-list-hoverForeground, var(--vscode-editorWidget-foreground, var(--vscode-foreground))) !important;
}
.toastui-editor-popup-add-image .toastui-editor-tabs .tab-item {
  color: var(--vscode-editorWidget-foreground, var(--vscode-foreground)) !important;
  border-bottom-color: var(--vscode-editorWidget-border, var(--vscode-widget-border)) !important;
}
.toastui-editor-popup-add-image .toastui-editor-tabs .tab-item.active {
  color: var(--vscode-textLink-foreground) !important;
  border-bottom-color: var(--vscode-textLink-foreground) !important;
}
.toastui-editor-popup-add-image .toastui-editor-file-name {
  background-color: var(--vscode-input-background) !important;
  border-color: var(--vscode-input-border, var(--vscode-widget-border)) !important;
  color: var(--vscode-input-placeholderForeground, var(--vscode-descriptionForeground)) !important;
}
.toastui-editor-popup-add-image .toastui-editor-file-name.has-file {
  color: var(--vscode-input-foreground) !important;
}
.toastui-editor-popup-add-image .toastui-editor-file-select-button {
  background-color: var(--vscode-button-secondaryBackground, var(--vscode-button-background)) !important;
  color: var(--vscode-button-secondaryForeground, var(--vscode-button-foreground)) !important;
  border-color: var(--vscode-button-border, var(--vscode-widget-border)) !important;
}
.toastui-editor-popup-add-table .toastui-editor-table-cell {
  background-color: var(--vscode-editorWidget-background) !important;
  border-color: var(--vscode-editorWidget-border, var(--vscode-widget-border)) !important;
}
.toastui-editor-popup-add-table .toastui-editor-table-cell.header {
  background-color: var(--vscode-sideBar-background, var(--vscode-editorWidget-background)) !important;
}
.toastui-editor-popup-add-table .toastui-editor-table-description {
  color: var(--vscode-editorWidget-foreground, var(--vscode-foreground)) !important;
}
.toastui-editor-context-menu {
  background-color: var(--vscode-menu-background, var(--vscode-editorWidget-background)) !important;
  color: var(--vscode-menu-foreground, var(--vscode-editorWidget-foreground, var(--vscode-foreground))) !important;
  border-color: var(--vscode-menu-border, var(--vscode-editorWidget-border, var(--vscode-widget-border))) !important;
}
.toastui-editor-context-menu li:not(.disabled):hover {
  background-color: var(--vscode-menu-selectionBackground, var(--vscode-list-hoverBackground)) !important;
  color: var(--vscode-menu-selectionForeground, var(--vscode-list-hoverForeground, var(--vscode-foreground))) !important;
}
`;

function escapeJsonForScript(json: string): string {
  return json.replace(/</g, "\\u003c");
}

/** GRD-VSC-006: Markdown-backed fields edited in the webview. */
function extractMarkdownFields(r: RequirementWithSource): Record<string, string> {
  const out: Record<string, string> = { description: r.description };
  const attrs =
    r.attributes && typeof r.attributes === "object" ? (r.attributes as Record<string, unknown>) : {};
  if ("rationale" in attrs && attrs.rationale != null) {
    out.rationale = String(attrs.rationale);
  }
  return out;
}

/** GRD-VSC-006: When this key is unchanged, only editable field text may differ — postMessage sync suffices. */
function requirementStructureKey(r: RequirementWithSource): string {
  const attrs = {
    ...(r.attributes && typeof r.attributes === "object" ? (r.attributes as Record<string, unknown>) : {}),
  };
  delete attrs.rationale;
  return JSON.stringify({
    id: r.id,
    title: r.title,
    links: r.links,
    parameters: r.parameters,
    attributes: attrs,
    hasRationale:
      r.attributes &&
      typeof r.attributes === "object" &&
      "rationale" in r.attributes &&
      (r.attributes as Record<string, unknown>).rationale != null,
  });
}

function parseRequirementFromText(
  uri: vscode.Uri,
  text: string
): RequirementWithSource {
  const data = parseYaml(text) as Record<string, unknown> | null;
  if (!data || typeof data !== "object") {
    throw new Error("Expected a YAML object with requirement fields.");
  }

  const id = data.id != null ? String(data.id) : undefined;
  const title = data.title != null ? String(data.title) : undefined;
  const description = data.description != null ? String(data.description) : "";

  if (!id) {
    throw new Error("Missing required field: id");
  }
  if (!title) {
    throw new Error("Missing required field: title");
  }

  // GRD-SYS-005: Parse parameters (name -> string | number | boolean) so preview resolves {{ :param }}.
  const parameters = normalizeParameters(data.parameters);

  const requirement: RequirementWithSource = {
    id,
    title,
    description,
    attributes:
      typeof data.attributes === "object" && data.attributes !== null
        ? (data.attributes as Record<string, unknown>)
        : undefined,
    links: Array.isArray(data.links) ? (data.links as RequirementWithSource["links"]) : undefined,
    parameters: parameters && Object.keys(parameters).length > 0 ? parameters : undefined,
    sourcePath: uri.fsPath,
  };

  return requirement;
}

/** GRD-SYS-005: Normalize YAML parameters to Record<string, ParameterValue>. */
function normalizeParameters(parameters: unknown): Record<string, ParameterValue> | undefined {
  if (parameters == null || typeof parameters !== "object" || Array.isArray(parameters)) {
    return undefined;
  }
  const out: Record<string, ParameterValue> = {};
  for (const [k, v] of Object.entries(parameters as Record<string, unknown>)) {
    if (typeof k !== "string" || !k.trim()) continue;
    if (v === null || v === undefined) continue;
    if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") {
      out[k] = v;
    }
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

export type OpenPreviewForIdFn = (requirementId: string) => Promise<void>;

export class RequirementPreviewManager {
  private panel: vscode.WebviewPanel | undefined;
  private currentDocumentUri: string | undefined;
  /** GRD-VSC-006: When unchanged, YAML edits only sync Toast fields without replacing webview HTML. */
  private lastStructureKey: string | undefined;
  private fieldEditFlushTimer: ReturnType<typeof setTimeout> | undefined;
  private pendingFieldEdits: Partial<Record<EditableMarkdownField, string>> = {};

  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly log: (message: string) => void,
    private readonly openPreviewForId: OpenPreviewForIdFn
  ) {
    const changeSub = vscode.workspace.onDidChangeTextDocument((e) => {
      if (this.currentDocumentUri !== e.document.uri.toString()) return;
      this.updatePreview(e.document);
    });

    // Do not subscribe to onDidSaveTextDocument: saves run after change events (and format-on-save),
    // and the save callback can see a different activeTextEditor than the YAML tab, which would push
    // syncFields into the webview and make Toast UI / the panel jump even when content did not change.

    const activeEditorSub = vscode.window.onDidChangeActiveTextEditor((editor) => {
      if (!editor) return;
      const doc = editor.document;
      if (!isRequirementDocument(doc)) return;
      // GRD-VSC-003: When user clicks a satisfies link, the target file opens and becomes active;
      // open the preview for that requirement if the panel did not exist yet.
      if (!this.panel) {
        this.openPreviewForDocument(doc);
        return;
      }
      const uri = doc.uri.toString();
      if (uri === this.currentDocumentUri) {
        if (this.panel) void this.updatePreview(doc, { forceFieldSync: true });
        return;
      }
      this.lastStructureKey = undefined;
      this.currentDocumentUri = uri;
      this.panel.title = previewTitle(doc.uri);
      this.updatePreview(doc);
    });

    context.subscriptions.push(changeSub, activeEditorSub);
  }

  openPreviewForDocument(document: vscode.TextDocument): void {
    if (!isRequirementDocument(document)) {
      this.log("[Gitreqd] Preview is only available for `.req.yml` or `.req.yaml` requirement files.");
      return;
    }

    const uriStr = document.uri.toString();
    if (this.currentDocumentUri !== uriStr) {
      this.lastStructureKey = undefined;
    }
    this.currentDocumentUri = uriStr;

    if (this.panel) {
      this.panel.title = previewTitle(document.uri);
      this.updatePreview(document);
      this.panel.reveal(this.panel.viewColumn ?? vscode.ViewColumn.Beside);
      return;
    }

    this.panel = vscode.window.createWebviewPanel(
      PREVIEW_VIEW_TYPE,
      previewTitle(document.uri),
      vscode.ViewColumn.Beside,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [this.context.extensionUri],
      }
    );

    this.context.subscriptions.push(this.panel);

    this.panel.onDidDispose(
      () => {
        this.panel = undefined;
        this.currentDocumentUri = undefined;
        this.lastStructureKey = undefined;
        if (this.fieldEditFlushTimer) clearTimeout(this.fieldEditFlushTimer);
      },
      undefined,
      this.context.subscriptions
    );

    this.panel.onDidChangeViewState(
      (e) => {
        if (!e.webviewPanel.active || !this.currentDocumentUri) return;
        const doc = vscode.workspace.textDocuments.find((d) => d.uri.toString() === this.currentDocumentUri);
        if (doc) void this.updatePreview(doc, { forceFieldSync: true });
      },
      undefined,
      this.context.subscriptions
    );

    this.panel.webview.onDidReceiveMessage(
      (msg: {
        type?: string;
        requirementId?: string;
        field?: string;
        value?: string;
      }) => {
        if (msg.type === "openPreview" && typeof msg.requirementId === "string") {
          this.openPreviewForId(msg.requirementId).catch((err) =>
            this.log(`[Gitreqd] Failed to open preview for ${msg.requirementId}: ${String(err)}`)
          );
          return;
        }
        if (
          msg.type === "fieldEdit" &&
          (msg.field === "description" || msg.field === "rationale") &&
          typeof msg.value === "string"
        ) {
          this.queueFieldEdit(msg.field, msg.value);
        }
      },
      undefined,
      this.context.subscriptions
    );

    this.updatePreview(document);
  }

  /** GRD-VSC-006: CSP, Toast UI assets, bootstrap JSON, editor module, and link handler. */
  private buildWebviewHtml(baseHtml: string, bootstrap: { fields: Record<string, string> }): string {
    if (!this.panel) return baseHtml;
    const w = this.panel.webview;
    const ext = this.context.extensionUri;
    const toastCssUri = w.asWebviewUri(vscode.Uri.joinPath(ext, "dist", "webview", "toastui-editor.css"));
    const editorJsUri = w.asWebviewUri(vscode.Uri.joinPath(ext, "dist", "webview", "editor-webview.js"));
    const csp = [
      `default-src 'none'`,
      `img-src ${w.cspSource} https: data:`,
      `style-src ${w.cspSource} 'unsafe-inline'`,
      `script-src ${w.cspSource}`,
      `font-src ${w.cspSource}`,
    ].join("; ");
    const escaped = escapeJsonForScript(JSON.stringify(bootstrap));
    const headInject = `
  <meta http-equiv="Content-Security-Policy" content="${csp}">
  <link rel="stylesheet" href="${toastCssUri}">
  <style>${PREVIEW_VSCODE_CHROME_STYLES}</style>
`;
    let html = baseHtml.replace("<head>", `<head>${headInject}`);
    const bodyAppend = `
  <script type="application/json" id="gitreqd-bootstrap">${escaped}</script>
  <script type="module" src="${editorJsUri}"></script>
  ${PREVIEW_LINK_SCRIPT}
`;
    if (html.includes("</body>")) {
      html = html.replace("</body>", `${bodyAppend}</body>`);
    } else {
      html = html + bodyAppend;
    }
    return html;
  }

  private queueFieldEdit(field: EditableMarkdownField, value: string): void {
    this.pendingFieldEdits[field] = value;
    if (this.fieldEditFlushTimer) clearTimeout(this.fieldEditFlushTimer);
    this.fieldEditFlushTimer = setTimeout(() => {
      this.fieldEditFlushTimer = undefined;
      void this.flushPendingFieldEdits();
    }, 280);
  }

  private async flushPendingFieldEdits(): Promise<void> {
    if (!this.panel || !this.currentDocumentUri) return;
    const pending = this.pendingFieldEdits;
    this.pendingFieldEdits = {};
    const keys = Object.keys(pending) as EditableMarkdownField[];
    if (keys.length === 0) return;

    const doc = vscode.workspace.textDocuments.find((d) => d.uri.toString() === this.currentDocumentUri);
    if (!doc) return;

    const text = doc.getText();
    let next = text;
    for (const field of keys) {
      const value = pending[field];
      if (value === undefined) continue;
      next = applyYamlMarkdownFieldUpdate(next, field, value);
    }
    if (next === text) return;

    const fullRange = new vscode.Range(doc.positionAt(0), doc.positionAt(text.length));
    const edit = new vscode.WorkspaceEdit();
    edit.replace(doc.uri, fullRange, next);
    await vscode.workspace.applyEdit(edit);
  }

  /**
   * @param options.forceFieldSync — When true, push field text to the webview (e.g. user focused the
   *   preview after editing YAML). Otherwise skip syncFields while the YAML editor is active or while
   *   the preview panel is focused: VS Code often keeps the YAML tab as activeTextEditor even when the
   *   user is typing in the WYSIWYG, which would echo document changes back into Toast and reset the
   *   editor on every keystroke.
   */
  private async updatePreview(
    document: vscode.TextDocument,
    options?: { forceFieldSync?: boolean }
  ): Promise<void> {
    if (!this.panel || this.currentDocumentUri !== document.uri.toString()) return;

    try {
      const requirement = parseRequirementFromText(
        document.uri,
        document.getText()
      );
      let allRequirements: RequirementWithSource[] | undefined;
      const folder = vscode.workspace.getWorkspaceFolder(document.uri);
      if (folder) {
        try {
          const result = await loadRequirements(folder.uri.fsPath);
          let list = result.requirements;
          const idx = list.findIndex((r) => r.id === requirement.id);
          if (idx >= 0) {
            list = [...list];
            list[idx] = requirement;
          } else {
            list = [requirement, ...list];
          }
          allRequirements = list;
        } catch {
          allRequirements = undefined;
        }
      }
      let profile: RequirementProfile = getRequirementProfile(STANDARD_PROFILE_ID);
      if (folder) {
        const projectRoot = await discoverProjectRoot(folder.uri.fsPath);
        if (projectRoot) {
          profile = loadActiveProfile(projectRoot);
        }
      }
      const sk = requirementStructureKey(requirement);
      const shouldFullRefresh = this.lastStructureKey === undefined || sk !== this.lastStructureKey;

      if (shouldFullRefresh) {
        this.lastStructureKey = sk;
        const baseHtml = profile.generateSingleRequirementHtml(requirement, allRequirements, {
          editableFieldMarkers: true,
        });
        this.panel.webview.html = this.buildWebviewHtml(baseHtml, {
          fields: extractMarkdownFields(requirement),
        });
      } else {
        if (!options?.forceFieldSync) {
          const yamlIsActiveEditor =
            vscode.window.activeTextEditor?.document.uri.toString() === document.uri.toString();
          const webviewIsFocused = this.panel.active;
          if (yamlIsActiveEditor || webviewIsFocused) return;
        }
        this.panel.webview.postMessage({
          type: "syncFields",
          fields: extractMarkdownFields(requirement),
        });
      }
    } catch (err) {
      this.lastStructureKey = undefined;
      const message = `[Gitreqd] Failed to render preview for ${document.uri.fsPath}: ${String(
        err
      )}`;
      this.log(message);
      this.panel.webview.html = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <title>Gitreqd requirement preview error</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 1rem; color: #b00020; }
            pre { white-space: pre-wrap; background: #fef2f2; padding: 0.75rem; border-radius: 4px; }
          </style>
        </head>
        <body>
          <h1>Could not render requirement preview</h1>
          <p>There was an error parsing the YAML or generating HTML:</p>
          <pre>${String(err)}</pre>
        </body>
        </html>
      `;
    }
  }

}

