/** GRD-BRW-001 + GRD-UI-002 + GRD-UI-003: Browser split-pane UI served by local provider. */
export const BROWSER_UI_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gitreqd browser UI</title>
  <link rel="stylesheet" href="/browser-ui.css">
</head>
<body>
  <div class="status"><span class="status-title">gitreqd browser</span><span id="status-count" class="status-meta">Requirements: -</span><span id="status-validation" class="status-meta">Validation: -</span></div>
  <div class="layout"><aside class="left"><div class="controls"></div><div id="tree-root"></div></aside><div id="sidebar-divider" class="divider" role="separator" aria-orientation="vertical" aria-label="Resize sidebar"></div><main class="right"><div id="detail-root">Select a requirement.</div></main></div>
  <script>
    const state = { requirements: [], byId: new Map(), selectedId: null, expandedDirs: new Set(), expandedReqs: new Set() };
    async function apiJson(path, options) { const res = await fetch(path, options); const body = await res.json(); if (!res.ok) throw new Error((body.error && body.error.message) || ("HTTP " + res.status)); return body; }
    function computeRelations(requirements) { const ids = new Set(requirements.map((r) => r.id)); const childrenByParent = new Map(); const incoming = new Set(); for (const r of requirements) for (const link of (r.links || [])) if (link && typeof link === "object" && typeof link.satisfies === "string") { const parentId = link.satisfies; if (!ids.has(parentId)) continue; incoming.add(r.id); if (!childrenByParent.has(parentId)) childrenByParent.set(parentId, []); childrenByParent.get(parentId).push(r.id); } return { childrenByParent, incoming }; }
    function groupRootsByDirectory(requirements, incoming) { const groups = new Map(); const add = (r) => { const key = (r.category || []).join("/") || "(root)"; if (!groups.has(key)) groups.set(key, []); groups.get(key).push(r.id); }; for (const r of requirements) { if (incoming.has(r.id)) continue; add(r); } if (groups.size === 0) { for (const r of requirements) add(r); } return new Map([...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]))); }
    function renderReqLabel(id, title) { const frag = document.createDocumentFragment(); const idSpan = document.createElement("span"); idSpan.className = "req-id"; idSpan.textContent = id; const titleSpan = document.createElement("span"); titleSpan.className = "req-title"; titleSpan.textContent = title; frag.append(idSpan, titleSpan); return frag; }
    function makeTreeNode(id, childrenByParent) { const req = state.byId.get(id); const row = document.createElement("div"); row.className = "tree-row"; const kids = (childrenByParent.get(id) || []).slice().sort(); const expanded = state.expandedReqs.has(id); const btn = document.createElement("button"); btn.className = "tree-row-btn" + (state.selectedId === req.id ? " active" : ""); const icon = document.createElement("span"); icon.className = "tree-icon"; icon.textContent = kids.length ? (expanded ? "▾" : "▸") : " "; if (kids.length) { icon.title = expanded ? "Collapse" : "Expand"; icon.onclick = (ev) => { ev.stopPropagation(); if (expanded) state.expandedReqs.delete(id); else state.expandedReqs.add(id); renderTree(); }; } const label = document.createElement("span"); label.className = "tree-select"; label.appendChild(renderReqLabel(req.id, req.title)); btn.append(icon, label); btn.onclick = () => selectRequirement(req.id); row.append(btn); const wrap = document.createElement("div"); wrap.appendChild(row); if (kids.length > 0 && state.expandedReqs.has(id)) { const ul = document.createElement("ul"); for (const childId of kids) { const li = document.createElement("li"); li.appendChild(makeTreeNode(childId, childrenByParent)); ul.appendChild(li); } wrap.appendChild(ul); } return wrap; }
    function renderTree() { const treeRoot = document.getElementById("tree-root"); treeRoot.innerHTML = ""; const rel = computeRelations(state.requirements); const groups = groupRootsByDirectory(state.requirements, rel.incoming); const ul = document.createElement("ul"); for (const [dir, ids] of groups.entries()) { const li = document.createElement("li"); const row = document.createElement("div"); row.className = "tree-row"; const expanded = state.expandedDirs.has(dir); const btn = document.createElement("button"); btn.className = "tree-row-btn"; const icon = document.createElement("span"); icon.className = "tree-icon"; icon.textContent = expanded ? "▾" : "▸"; icon.onclick = (ev) => { ev.stopPropagation(); if (expanded) state.expandedDirs.delete(dir); else state.expandedDirs.add(dir); renderTree(); }; const label = document.createElement("span"); label.className = "tree-select"; label.textContent = dir; btn.append(icon, label); btn.onclick = () => { if (expanded) state.expandedDirs.delete(dir); else state.expandedDirs.add(dir); renderTree(); }; row.append(btn); li.appendChild(row); if (expanded) { const inner = document.createElement("ul"); for (const id of ids.sort()) { const reqLi = document.createElement("li"); reqLi.appendChild(makeTreeNode(id, rel.childrenByParent)); inner.appendChild(reqLi); } li.appendChild(inner); } ul.appendChild(li); } treeRoot.appendChild(ul); }
    async function refreshStatus() { const status = await apiJson("/api/status"); document.getElementById("status-count").textContent = "Requirements: " + status.requirementCount; const validation = document.getElementById("status-validation"); const hasErrors = Boolean(status.errors && status.errors.length); validation.textContent = hasErrors ? ("Validation: " + status.errors.length + " error(s)") : "Validation: OK"; validation.classList.toggle("error", hasErrors); }
    function renderLinkEditor(requirement) { const root = document.createElement("div"); root.className = "section"; root.innerHTML = "<h3>Edit links</h3>"; const existing = document.createElement("div"); for (const link of (requirement.links || [])) { const chip = document.createElement("span"); chip.className = "chip mono"; chip.textContent = JSON.stringify(link); const removeBtn = document.createElement("button"); removeBtn.textContent = "x"; removeBtn.onclick = async () => { await apiJson("/api/requirements/" + encodeURIComponent(requirement.id) + "/links", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ operation: "remove", link }) }); await loadData(requirement.id); }; chip.appendChild(removeBtn); existing.appendChild(chip); } const row = document.createElement("div"); const keyInput = document.createElement("input"); keyInput.placeholder = "key"; const valueInput = document.createElement("input"); valueInput.placeholder = "value"; const addBtn = document.createElement("button"); addBtn.textContent = "Add link"; addBtn.onclick = async () => { const key = keyInput.value.trim(); const value = valueInput.value.trim(); if (!key || !value) return; const link = {}; link[key] = value; await apiJson("/api/requirements/" + encodeURIComponent(requirement.id) + "/links", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ operation: "add", link }) }); keyInput.value = ""; valueInput.value = ""; await loadData(requirement.id); }; row.append(keyInput, valueInput, addBtn); root.append(existing, row); return root; }
    async function renderDetail() { const root = document.getElementById("detail-root"); root.innerHTML = ""; if (!state.selectedId) { root.textContent = "Select a requirement."; return; } const req = state.byId.get(state.selectedId); if (!req) { root.textContent = "Requirement not found."; return; } const rendered = await apiJson("/api/requirements/" + encodeURIComponent(req.id) + "/rendered-detail"); const detailWrap = document.createElement("div"); detailWrap.className = "detail-report"; detailWrap.innerHTML = rendered.html || ""; detailWrap.onclick = (ev) => { const target = ev.target; if (!(target instanceof Element)) return; const link = target.closest("a[href^='#']"); if (!link) return; const href = link.getAttribute("href") || ""; const id = href.startsWith("#") ? href.slice(1) : ""; if (!id || !state.byId.has(id)) return; ev.preventDefault(); selectRequirement(id); }; root.appendChild(detailWrap); root.appendChild(renderLinkEditor(req)); }
    function getSelectedIdFromUrl() { const params = new URLSearchParams(window.location.search); const value = params.get("req"); return value && value.trim() ? value.trim() : null; }
    function updateUrlForSelection(id, replace) { const next = new URL(window.location.href); if (id) next.searchParams.set("req", id); else next.searchParams.delete("req"); if (replace) window.history.replaceState({ selectedId: id }, "", next); else window.history.pushState({ selectedId: id }, "", next); }
    function selectRequirement(id, options) { const opts = options || {}; if (!id || !state.byId.has(id)) return; const same = state.selectedId === id; state.selectedId = id; if (!opts.silentHistory) { if (same) updateUrlForSelection(id, true); else updateUrlForSelection(id, Boolean(opts.replaceHistory)); } void renderDetail(); renderTree(); }
    async function loadData(keepId) { const data = await apiJson("/api/requirements"); state.requirements = data.requirements || []; state.byId = new Map(state.requirements.map((r) => [r.id, r])); if (state.expandedDirs.size === 0) for (const req of state.requirements) state.expandedDirs.add((req.category || []).join("/") || "(root)"); const urlId = getSelectedIdFromUrl(); const selected = keepId && state.byId.has(keepId) ? keepId : (urlId && state.byId.has(urlId) ? urlId : (state.selectedId && state.byId.has(state.selectedId) ? state.selectedId : null)); state.selectedId = selected; if (selected) updateUrlForSelection(selected, true); renderTree(); await renderDetail(); await refreshStatus(); }
    function initDividerResize() { const divider = document.getElementById("sidebar-divider"); let resizing = false; const minWidth = 260; const maxWidth = 640; divider.addEventListener("mousedown", () => { resizing = true; }); window.addEventListener("mouseup", () => { resizing = false; }); window.addEventListener("mousemove", (ev) => { if (!resizing) return; const next = Math.max(minWidth, Math.min(maxWidth, ev.clientX)); document.documentElement.style.setProperty("--sidebar-width", next + "px"); }); }
    window.addEventListener("popstate", () => { const nextId = getSelectedIdFromUrl(); if (nextId && state.byId.has(nextId)) { selectRequirement(nextId, { silentHistory: true }); } else { state.selectedId = null; void renderDetail(); renderTree(); } });
    initDividerResize();
    loadData(getSelectedIdFromUrl());
  </script>
</body>
</html>`;
